# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MAC <- function(treedata) {
    .Call('HMTGO_MAC', PACKAGE = 'HMTGO', treedata)
}

tree_transformation <- function(children_db, genes_db, root) {
    .Call('HMTGO_tree_transformation', PACKAGE = 'HMTGO', children_db, genes_db, root)
}

getPDEC <- function(condProb, parentIndex, componMappingMat, sepLocation, formula) {
    .Call('HMTGO_getPDEC', PACKAGE = 'HMTGO', condProb, parentIndex, componMappingMat, sepLocation, formula)
}

HMTEMC <- function(optim_R, likelihoodfunc_Alt, likelihoodfunc_Null, init, pval, depth, leaf, nonleaf, childrenIndexMat, propInParent, childrenCount, parentIndex, nDAG, betaTemp = 1, null_dist = "Mixture", penalty = FALSE, num_method = "Nelder-Mead", max_it = 200L, innerit = 1000L, conv_threshold = 1e-8) {
    .Call('HMTGO_HMTEMC', PACKAGE = 'HMTGO', optim_R, likelihoodfunc_Alt, likelihoodfunc_Null, init, pval, depth, leaf, nonleaf, childrenIndexMat, propInParent, childrenCount, parentIndex, nDAG, betaTemp, null_dist, penalty, num_method, max_it, innerit, conv_threshold)
}

getNegNullLlikeC <- function(x, pval, weight, m_c = 0) {
    .Call('HMTGO_getNegNullLlikeC', PACKAGE = 'HMTGO', x, pval, weight, m_c)
}

getNegAltLlikeC <- function(x, pval, weight, penalty) {
    .Call('HMTGO_getNegAltLlikeC', PACKAGE = 'HMTGO', x, pval, weight, penalty)
}

HMT_DAEMC <- function(pval, treedata, optim_R, likelihoodfunc_Alt, likelihoodfunc_Null, schedule, init_origin, penalty = FALSE, null_dist = "Mixture", num_method = "Nelder-Mead", iternum_final = 1000L, iternum_hot = 100L, iternum_inner = 1000L, conv_threshold = 1e-8) {
    .Call('HMTGO_HMT_DAEMC', PACKAGE = 'HMTGO', pval, treedata, optim_R, likelihoodfunc_Alt, likelihoodfunc_Null, schedule, init_origin, penalty, null_dist, num_method, iternum_final, iternum_hot, iternum_inner, conv_threshold)
}

